### ISSUE TITLE
Backoffice: Добавити генерацію Id замовлення при створенні нового замовлення

### ISSUE THREAD

**Issue by mvoronovpolytech** [Net-532/kakadu#115]
1. Реалізувати приватний метод  `getNextOrderId()` в OrderRepositoryXML, подібний до `getNextOrderNumber()`
Даний метод має повенути максимальний + 1 **ID** замовлення, яке знаходиться у файлі з тестовими данними.
2. При збереженні замовлення в методі `Save` ставити id замовленню = `getNextOrderId()`

**Comment by Pozzaza** [comment]
Виконав.
