### ISSUE TITLE
Генерація id продукта при створенні нового

### ISSUE THREAD

**Issue by mvoronovpolytech** [Net-532/kakadu#132]
Реалізувати приватний метод `getNextProductId()` в `ProductRepositoryXML`, подібний до `getNextOrderNumber()` в `OrderRepositoryXML`
    Даний метод має повенути максимальний + 1 ID продукту яке знаходиться у файлі з тестовими данними.
    При збереженні продукту в методі `Save` ставити id продукту = getNextProductId()

**Comment by Pozzaza** [comment]
Виконав.
