### ISSUE TITLE
Backoffice: Вдосконалити редагування продуктів

### ISSUE THREAD

**Issue by mvoronovpolytech** [Net-532/kakadu#159]
1. При натисканні відміни редагування продуктів час від часу з'являється повідомлення з помилкою `"Can't add new product.`
2. При переході з таблиці продуктів, до таблиці  замовлень, а потів назад до таблиці продуктів додються додаткові події, і при натиснені кнопки додати, або редагувати - відкривається вікно стільки разів, скількі переходів з таблиці в таблицю користувач зробив

**Comment by Pozzaza** [comment]
Виправлено.
